config/routes.rb
require 'sidekiq/web'

class AdminConstraint
  def matches?(request)
    admin_id = request.session[:admin_id]
  end
end

Rails.application.routes.draw do
  mount Sidekiq::Web => 'admin/sidekiq'
  root "pages#index"
  resources :reviews
  resources :rooms do
    resources :bookings
  end

  get '/bookings', to: 'bookings#choose_room'

  devise_for :admin, path: 'admin', controllers: {
            registrations: 'admin/registrations'
          }, :sign_out_via => [ :get ]
  namespace :admin do
    resources :reviews do
      member do
        get :toggle_status
      end
    end
    resources :bookings do
      member do
        get :toggle_status
      end
    end
    resources :rooms, :bookings, :reviews
    get '/admin/dashboard', as: :authenticated_root
    get 'dashboard', to: 'pages#dashboard'
    get 'statistic_csv(.:format)', to: 'files_for_bookings#download'
    get 'statistic_pdf(.:format)', to: 'pdf_for_bookings#download', as: "download_pdf"
  end
  unauthenticated :admin do
    namespace :admin do
      root :to => 'session#new', as: :unauthenticated_root
    end
  end
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  has_many :bookings
  has_many_attached :images
  validates :name, :description, :price, :short_description, presence: true
  paginates_per 2

  def self.available_rooms(start_date, last_date)
    Booking.excluded_id(start_date, last_date)
  end

  def images_as_thumbnails(image)
    return unless image.content_type.in?(%w[image/jpg image/jpeg image/png])

    image.variant(resize_to_limit: [400, 400]).processed
  end
end

app/controllers/admin/rooms_controller.rb
# frozen_string_literal: true

class Admin::RoomsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_room, only: %i[show edit update destroy]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all.with_attached_images
  end

  # GET /rooms/1 or /rooms/1.json
  def show; end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
    @room = Room.find(params[:id])
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to admin_rooms_url(@room), notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to admin_rooms_url, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to admin_rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_room
    @room = Room.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def room_params
    params.require(:room).permit(:name, :description, :short_description, :price, images: [])
  end
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

class RoomsController < ApplicationController
  before_action :set_room, only: %i[show]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all.order(:created_at).page params[:page]
  end

  # GET /rooms/1 or /rooms/1.json
  def show
    @booking = Booking.new
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_room
    @room = Room.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def room_params
    params.require(:room).permit(:name, :description, :price, :short_description, images: [])
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/admin/rooms/_form.html.erb
<%= form_for :article, url: articles_path, data: {turbo:false} do |f| %>
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>
    <div>
      <%= form.label :short_description, style: "display: block" %>
      <%= form.text_area :short_description %>
    </div>
  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>
    <div>
      <%= form.label :images %>
      <%= form.file_field :images, multiple: true%>
    </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/rooms/_room.html.erb
<div id="<%= dom_id room %>">
  <p>
    <strong>Name:</strong>
    <%= room.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= room.description %>
  </p>
  <p>
    <strong>Short description:</strong>
    <%= room.short_description %>
  </p>
  <p>
    <strong>Price:</strong>
    <%= room.price %>
  </p>

  <p>
    <% room.images.each do |image|%>
      <%= link_to image_tag(image, style:"width:550px; height:400px"), image %>
      <%end%>
  </p>



</div>

app/views/admin/rooms/edit.html.erb
<%= render 'layouts/navigation_for_admin' %>
<h1>Editing room</h1>
  <% if @room.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% @room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<%= form_for :room, url:  admin_room_path(@room), method: :put, data: {turbo:false} do |form| %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :short_description, style: "display: block" %>
    <%= form.text_area :short_description %>
  </div>

  <div>
    <%= form.label "Add images:", style: "display: block" %>
    <%= form.file_field :images, multiple: true %><br>
  </div>
  <div>
    <%= form.submit%>
  </div>
<% end %>

<br>

<div>
  <%= link_to "Back to rooms", admin_rooms_path %>
</div>
<div>
  <%= link_to "Create new room", new_admin_room_path %>
</div>

app/views/admin/rooms/index.html.erb
<%= render 'layouts/navigation_for_admin' %>
<p style="color: green"><%= notice %></p>

<h1 align="center">List of rooms</h1>

  <table class="table">
    <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Date of create</th>
      <th scope="col">Last update</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
    </thead>

    <tbody>
    <% @rooms.each do |room| %>
    <tr>
      <td> <%= link_to  room.name, admin_room_path(room) %></td>
      <td> <%= room.created_at %></td>
      <td> <%= room.updated_at %></td>
      <td> <%= button_to "Edit", edit_admin_room_path(room),method: :get, class: "btn btn-xs btn-primary" %>&nbsp; </td>
      <td> <%= button_to "Delete", admin_room_path(room), method: :delete, data: { confirm: "Are you sure you want to delete this room?"}, class: "btn btn-xs btn-danger" %>
      </td>
    </tr>
    <% end %>
   </tbody>
  </table>

app/views/admin/rooms/new.html.erb
<%= render 'layouts/navigation_for_admin' %>
<h1>New room</h1>
<%= form_for :room, url: admin_rooms_url, data: {turbo:false} do |form| %>
    <% if @room.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

        <ul>
          <% @room.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>

    <div>
      <%= form.label :description, style: "display: block" %>
      <%= form.text_area :description %>
    </div>

  <div>
    <%= form.label :short_description, style: "display: block" %>
    <%= form.text_area :short_description %>
  </div>


  <div>
      <%= form.label :price, style: "display: block" %>
      <%= form.number_field :price %>
    </div>
  <br>
      <div>
        <%= form.label "Add images:", style: "display: block" %>
        <%= form.file_field :images, multiple: true %><br>
  </div>
  <br>
    <div>
      <%= form.submit %>
    </div>
  <% end %>

<br>

<div>
  <%= link_to "Back to rooms", admin_rooms_url %>
</div>

app/views/admin/rooms/show.html.erb
<%= render 'layouts/navigation_for_admin' %>
<p style="color: green"><%= notice %></p>

<%= render @room %>

<div>
  <%= link_to "Edit this room", edit_admin_room_path(@room) %> |
  <%= link_to "Back to rooms", admin_rooms_path %>

  <%= button_to "Destroy this room", @room, method: :delete %>
</div>