config/routes.rb
require 'sidekiq/web'

class AdminConstraint
  def matches?(request)
    admin_id = request.session[:admin_id]
  end
end

Rails.application.routes.draw do
  mount Sidekiq::Web => 'admin/sidekiq'
  root "pages#index"
  resources :reviews
  resources :rooms do
    resources :bookings
  end

  get '/bookings', to: 'bookings#choose_room'

  devise_for :admin, path: 'admin', controllers: {
            registrations: 'admin/registrations'
          }, :sign_out_via => [ :get ]
  namespace :admin do
    resources :reviews do
      member do
        get :toggle_status
      end
    end
    resources :bookings do
      member do
        get :toggle_status
      end
    end
    resources :rooms, :bookings, :reviews
    get '/admin/dashboard', as: :authenticated_root
    get 'dashboard', to: 'pages#dashboard'
    get 'statistic_csv(.:format)', to: 'files_for_bookings#download'
    get 'statistic_pdf(.:format)', to: 'pdf_for_bookings#download', as: "download_pdf"
  end
  unauthenticated :admin do
    namespace :admin do
      root :to => 'session#new', as: :unauthenticated_root
    end
  end
end

app/controllers/admin/reviews_controller.rb
# frozen_string_literal: true

class Admin::ReviewsController < ApplicationController
  attr_reader :review

  before_action :authenticate_admin!
  before_action :set_review, only: %i[show edit update destroy]
  # GET /reviews or /reviews.json
  def index
    @reviews = Review.all.order('reviews.created_at desc')
  end

  def update
    # @review
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to review_url(@review), notice: 'Review was successfully updated.' }

      end
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    @review.destroy

    respond_to do |format|
      format.html { redirect_to "/admin/reviews", notice: 'Review was successfully destroyed.' }
    end
  end

  def toggle_status
    @review = Review.find(params[:id])
    if @review.pended?
      @review.published!
    elsif @review.published?
      @review.pended!
    end

    redirect_to admin_reviews_url, notice: 'Review status has been updated.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_review
    @review = Review.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def review_params
    params.require(:review).permit(:author_name, :author_email, :body, :toggle_status)
  end
end

app/controllers/reviews_controller.rb
# frozen_string_literal: true

class ReviewsController < ApplicationController
  before_action :set_review, only: %i[show edit update destroy]
  # GET /reviews or /reviews.json
  def index
    @reviews = Review.all.published.order(created_at: :desc).page params[:page]
  end

  # GET /reviews/1 or /reviews/1.json
  def show
    @review = Review.find(params[:id])
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # POST /reviews or /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to review_url(@review), notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_review
    @review = Review.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def review_params
    params.require(:review).permit(:author_name, :author_email, :body)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/reviews/index.html.erb
<p style="color: green"><%= notice %></p>
<%= render 'layouts/navigation_for_admin' %>
<h1 align="center">Reviews</h1>

<table class="table">
  <thead>
  <tr>
    <th scope="col">Author's name</th>
    <th scope="col">Author's email</th>
    <th scope="col">Review's body</th>
    <th scope="col">Status</th>
    <th scope="col">Change status</th>
    <th scope="col">Delete</th>
  </tr>
  </thead>

  <tbody>
  <% @reviews.each do |review| %>
    <tr>
      <td> <%= review.author_name %></td>
      <td> <%= review.author_email%></td>
      <td> <%= review.body.first(80) %></td>
      <td> <%= review.status %></td>
<!--      <td> <%#= link_to review.status, toggle_status_admin_review_path(review) %>&nbsp; </td>-->
      <td> <%= button_to "Change status", toggle_status_admin_review_path(review), method: :get, class: "btn btn-xs btn-warning" %>
      <td> <%= button_to "Delete", admin_review_path(review), method: :delete, data: { confirm: "Are you sure you want to delete this review?"}, class: "btn btn-xs btn-danger" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>