config/routes.rb
require 'sidekiq/web'

class AdminConstraint
  def matches?(request)
    admin_id = request.session[:admin_id]
  end
end

Rails.application.routes.draw do
  mount Sidekiq::Web => 'admin/sidekiq'
  root "pages#index"
  resources :reviews
  resources :rooms do
    resources :bookings
  end

  get '/bookings', to: 'bookings#choose_room'

  devise_for :admin, path: 'admin', controllers: {
            registrations: 'admin/registrations'
          }, :sign_out_via => [ :get ]
  namespace :admin do
    resources :reviews do
      member do
        get :toggle_status
      end
    end
    resources :bookings do
      member do
        get :toggle_status
      end
    end
    resources :rooms, :bookings, :reviews
    get '/admin/dashboard', as: :authenticated_root
    get 'dashboard', to: 'pages#dashboard'
    get 'statistic_csv(.:format)', to: 'files_for_bookings#download'
    get 'statistic_pdf(.:format)', to: 'pdf_for_bookings#download', as: "download_pdf"
  end
  unauthenticated :admin do
    namespace :admin do
      root :to => 'session#new', as: :unauthenticated_root
    end
  end
end

app/models/booking.rb
# frozen_string_literal: true

class Booking < ApplicationRecord
  enum status: { pended: 0, accepted: 1 }
  belongs_to :room
  before_validation :dates_is_blank
  before_validation :rooms_are_available
  validates :start_date, :last_date, :status, :user_name, :user_email, :room_id, presence: true

  def date_restrictions
    if Date.today > start_date
      errors.add(:start_date, "Check-in date should be greater or equal to today's date")
    elsif last_date.to_date < start_date.to_date
      errors.add(:last_date, 'Check-out date should be greater than Check-in date')
    end
  end

  # get the all the room_id which room are booked in between start_date and last_date
  def self.excluded_id(start_date, last_date)
    # if array is empty return true else return the array
    if (@book_room = Booking.where('Date(start_date) < ? AND Date(last_date) > ? ', last_date,
                                   start_date).map(&:room_id)).empty?
      []
    else
      @book_room
    end
  end

  def rooms_are_available
    @booked_rooms = Room.available_rooms(start_date, last_date)
    if @booked_rooms.empty?
      true
    else
      @booked_rooms.include?(room_id)
      errors.add(:room_id, 'This room is not available on the selected dates.')
      false
    end
  end

  def dates_is_blank
        date_restrictions if start_date.present? && last_date.present?
  end
end

app/controllers/admin/bookings_controller.rb
# frozen_string_literal: true

class Admin::BookingsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_booking, only: %i[show edit update destroy]

  # GET /bookings or /bookings.json
  def index
    @bookings = Booking.all.order('bookings.created_at desc')
    @caclulations = CalculateDailyStatService.new.calculate
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update_columns(status)
         format.html { redirect_to admin_bookings_url, notice: 'Booking was successfully updated.' }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to admin_bookings_url, notice: 'Booking was successfully destroyed.' }
    end
  end

  def toggle_status
    @booking = Booking.find(params[:id])
    if @booking.pended?
      @booking.update_columns(status: 1)
      BookingsCsvJob.perform_later
    elsif @booking.accepted?
      @booking.update_columns(status: 0)
    end
    redirect_to admin_bookings_url, notice: 'Booking status has been updated.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_booking
    @booking = Booking.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def booking_params
    params.require(:booking).permit(:start_date, :last_date, :room_id)
  end
end

app/controllers/bookings_controller.rb
# frozen_string_literal: true

class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show edit update destroy]

  # GET /bookings/1 or /bookings/1.json
  def show
    @room = @booking.room
  end

  # GET /bookings/new
  def new
    @rooms = Room.all
    @booking = Booking.new
    @room = @booking.room
  end

  # POST /bookings or /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html do
          redirect_to room_booking_path(@booking.room_id, @booking), notice: 'Booking was successfully created.'
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def toggle_status
    @booking = Booking.find(params[:id])
    if @booking.pended?
      @booking.accepted!
    elsif @booking.accepted?
      @booking.pended!
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_booking
    @booking = Booking.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def booking_params
    params.require(:booking).permit(:user_name, :user_email, :start_date, :last_date, :room_id)
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_booking.html.erb
<div id="<%= dom_id booking %>">
  <%@room = Room.find(params[:room_id]) %>

<div class="b-example-divider"></div>
<div class="modal modal-tour position-static d-block bg-secondary py-5" tabindex="-1" role="dialog" id="modalTour">
  <div class="modal-dialog" role="document">
    <div class="modal-content rounded-4 shadow">
      <div class="modal-body p-5">
        <h2 class="fw-bold mb-0">Your booking:</h2>

        <ul class="d-grid gap-4 my-5 list-unstyled">
          <li class="d-flex gap-4">
            <div>
              <h5 class="mb-0">Name</h5>
              <%= booking.user_name %>
            </div>
          </li>
          <li class="d-flex gap-4">
            <div>
              <h5 class="mb-0">Email</h5>
              <%=booking.user_email%>
            </div>
          </li>
          <li class="d-flex gap-4">
            <div>
              <h5 class="mb-0">Check-in & check-out dates</h5>
              <%=booking.start_date%> - <%=booking.last_date%>
            </div>
          </li>
          <li class="d-flex gap-4">
            <div>
              <h5 class="mb-0">Room</h5>
              <%= @room.name %>
            </div>
          </li>
        </ul>
        <%= button_to "Great, thanks!", rooms_path, method: :get, class: "btn btn-lg btn-success mt-5 w-100"%>
      </div>
    </div>
  </div>
</div>

</div>

app/views/bookings/choose_room.html.erb
<%= render 'layouts/navigation' %>

<div class="text-center">
  <h1>Choose room first </h1>
<%= button_to "Click here to choose room", rooms_path, method: :get, class: "btn btn-outline-dark flex-shrink-0"%>
</div>

app/views/bookings/index.html.erb
<p style="color: green"><%= notice %></p>
<%= render 'layouts/navigation' %>

<h1>Bookings</h1>

<div id="bookings">
  <% @bookings.each do |booking| %>
    <%= render booking %>
    <p>
      <%= link_to "Show this booking", booking %>
    </p>
  <% end %>
</div>

<%= link_to "New booking", new_booking_path %>

app/views/bookings/new.html.erb
<%= render 'layouts/navigation' %>

<div class="container">
   <%= form_for :booking, url: room_bookings_path, data: {turbo:false} do |form| %>
      <% if @booking.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>
      <ul>
        <% @booking.errors.each do |error| %>
          <li><%=  error.full_message  %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <%= render 'rooms/show' %>

    <div class="py-5 text-center">

      <h2>Booking form for room  </h2>
      <p class="lead">Please complete the fields below.</p>
    </div>
  <%@room = Room.find(params[:room_id]) %>



  <div class="container-sm">

    <form>

      <!-- Name input -->
      <div class="form-outline mb-4">

        <label class="form-label" for="form4Example1">Name</label>
        <input type="text" id="form4Example1" class="form-control" name="booking[user_name]" />
      </div>

      <!-- Email input -->
      <div class="form-outline mb-4">
        <label class="form-label" for="form4Example2">Email address</label>
        <input type="email" id="form4Example2" class="form-control"name="booking[user_email]" />
      </div>

      <div>
        <%= form.label "Choose check_in date", style: "display: block" %>
        <%= form.date_field :start_date %>
      </div>

      <div>
        <%= form.label "Choose check_out date", style: "display: block" %>
        <%= form.date_field :last_date %>
      </div>

      <div>
        <input name="booking[room_id]" value="<%=params[:room_id] %>" type="hidden">
      </div>
      <%@booking.room_id = params[:room_id] %>
      <!-- Submit button -->
      <button type="submit" class="btn w-100 btn btn-success btn-block mb-4">Submit</button>

    </form>
  <% end %>
    </div>
</div>

app/views/bookings/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render 'layouts/navigation' %>

<%= render @booking %>