config/routes.rb
require 'sidekiq/web'

class AdminConstraint
  def matches?(request)
    admin_id = request.session[:admin_id]
  end
end

Rails.application.routes.draw do
  mount Sidekiq::Web => 'admin/sidekiq'
  root "pages#index"
  resources :reviews
  resources :rooms do
    resources :bookings
  end

  get '/bookings', to: 'bookings#choose_room'

  devise_for :admin, path: 'admin', controllers: {
            registrations: 'admin/registrations'
          }, :sign_out_via => [ :get ]
  namespace :admin do
    resources :reviews do
      member do
        get :toggle_status
      end
    end
    resources :bookings do
      member do
        get :toggle_status
      end
    end
    resources :rooms, :bookings, :reviews
    get '/admin/dashboard', as: :authenticated_root
    get 'dashboard', to: 'pages#dashboard'
    get 'statistic_csv(.:format)', to: 'files_for_bookings#download'
    get 'statistic_pdf(.:format)', to: 'pdf_for_bookings#download', as: "download_pdf"
  end
  unauthenticated :admin do
    namespace :admin do
      root :to => 'session#new', as: :unauthenticated_root
    end
  end
end

app/views/layouts/_navigation.html.erb
<header>

  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top mask-custom shadow-0">
    <div class="container">
      <a class="navbar-brand" href="/"><span style="color: #696969;">Hotel</span><span style="color:#BC8F8F;"> Grand Budapest</span></a>
      <button class="navbar-toggler" type="button" data-mdb-toggle="collapse"
              data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
              aria-label="Toggle navigation">
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/reviews">Reviews</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/rooms">Rooms</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="/bookings">Bookings</a>
          </li>
        </ul>

      </div>
    </div>
  </nav>

  <section>
<!--    Intro-->
    <div id="intro" class="bg-image " style="
    background-image: url('https://phonoteka.org/uploads/posts/2022-01/1643003484_1-phonoteka-org-p-bledno-rozovii-odnotonnii-fon-1.jpg');
      height: 5vh">
      <div class="mask" style="background-color: rgba(250, 182, 162, 0.15);"></div>
    </div>

  </section>

</header>

app/views/layouts/_navigation_for_admin.html.erb
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <%= link_to "Hotel Grand Budapest", admin_dashboard_path, class: "navbar-brand", id: "logo" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">

            <li class="nav-item">
              <a class="nav-link" href="/admin/rooms">List of rooms</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/admin/rooms/new">Add new room</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/admin/reviews">Reviews</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="/admin/bookings">List of bookings</a>
            </li>
          </ul>
          <ul class="nav justify-content-end">
            <% if admin_signed_in? %>
              <li class="nav-item">
                <a class="text-success">Hello, admin | <%= link_to "Log out", destroy_admin_session_path, data: {"turbo-method": :delete } %></a>
            <% else %>
              <%= link_to "Sign in", new_admin_session_path %>
            <% end %>
            </li>
          </ul>

        </div>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hotel</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  </head>

  <body>
   <p class=”notice”><%= notice %></p>
  <p class=”alert”><%= alert %></p>
    <%= yield %>
  </body>



</html>